version: "3.7"

networks:
  Catena-network:

services:
  seed:
    networks:
      - Catena-network
    image: ReshiAdavan/Catena
    volumes:
      - ~/Development/scala/Catena/:/tmp/Catena
    ports:
      - "2552:2552"
      - "8000:8000"
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: seed
      CLUSTER_SEED_IP: seed
      CATENA_PERSISTENCE_DIR: "/persistence/seed/journal"
      CATENA_SNAPSHOTS_DIR: "/persistence/seed/snapshots"
    command: ["local", "/tmp/Catena"]

  node1:
    networks:
      - Catena-network
    image: ReshiAdavan/Catena
    volumes:
      - ~/Development/scala/Catena/:/tmp/Catena
    ports:
      - "8001:8000"
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node1
      CLUSTER_PORT: 1600
      CLUSTER_SEED_IP: seed
      CLUSTER_SEED_PORT: 2552
      CATENA_NODE_ID: node1
      CATENA_PERSISTENCE_DIR: "/persistence/node1/journal"
      CATENA_SNAPSHOTS_DIR: "/persistence/node1/snapshots"
    command: ["local", "/tmp/Catena"]

  node2:
    networks:
      - Catena-network
    image: ReshiAdavan/Catena
    volumes:
      - ~/Development/scala/Catena/:/tmp/Catena
    ports:
      - "8002:8000"
    environment:
      SERVER_IP: 0.0.0.0
      CLUSTER_IP: node2
      CLUSTER_PORT: 1600
      CLUSTER_SEED_IP: seed
      CLUSTER_SEED_PORT: 2552
      CATENA_NODE_ID: node2
      CATENA_PERSISTENCE_DIR: "/persistence/node2/journal"
      CATENA_SNAPSHOTS_DIR: "/persistence/node2/snapshots"
    command: ["local", "/tmp/Catena"]
